### ISSUE TITLE
INSTALL_FAILED_NO_MATCHING_ABIS: Failed to extract native

### ISSUE THREAD

**Issue by bluesiboy** [AmosHuKe/Mood-Example#10]
此项目不能在虚拟机运行啊？ 是哪个包的限制了？？

**Comment by AmosHuKe** [comment]
> 此项目不能在虚拟机运行啊？是哪个包的限制了？？

麻烦问下，用的哪个版本的模拟器，我复现一下。

**Comment by bluesiboy** [comment]
> > 此项目不能在虚拟机运行啊？是哪个包的限制了？？
> 
> 麻烦问下，用的哪个版本的模拟器，我复现一下。

![image](https://user-images.githubusercontent.com/9855885/170984245-650b6b79-263e-41c9-8484-17cd518799b8.png)

**Comment by AmosHuKe** [comment]
@bluesiboy 找到原因了，是因为没有指定 `x86_64` 的 abi。  
你可以在这里进行修改：`android\app\build.gradle`   
```
android {
    ...
    defaultConfig {
        ...
        ndk {
            abiFilters 'x86','x86_64','armeabi-v7a',‘arm64-v8a’
        }
    }
}
```

晚些，我会提交这个更新，再次感谢你的反馈！
