### ISSUE TITLE
关于放大系统字体导致的文字显示的问题

### ISSUE THREAD

**Issue by dsxksss** [AmosHuKe/Mood-Example#11]
![Screenshot_2022-06-30-00-53-02-622_com.example.moodexample.jpg](https://user-images.githubusercontent.com/73477803/176493030-29f0918f-a877-43d4-8294-715c2e5f7e79.jpg)

**Comment by AmosHuKe** [comment]
@dsxksss 感谢！
已修复（非锁定全局字体缩放），
将系统最大最小字体，多语言（比如英文有些单词很长）都做了适配。
