### ISSUE TITLE
这个项目也太强了吧！！

### ISSUE THREAD

**Issue by user1121114685** [AmosHuKe/Mood-Example#12]
体验了下 直接卧槽 牛逼！！！

**Comment by AmosHuKe** [comment]
感谢认可 😆

**Comment by liu12151407** [comment]
我现在维护Android+uniSdk和IOS+uniSdk 人都麻了，打算直接Flutter+uniSdk重构了，这个项目很有参考价值哦，666

**Comment by AmosHuKe** [comment]
@liu12151407 这个项目集成得很基础，实际上还有一些坑要踩，加油吧！

**Comment by liu12151407** [comment]
> @liu12151407 这个项目集成得很基础，实际上还有一些坑要踩，加油吧！

嗯，有些我调整了一下，目前资产管理，我用的 fam ，数据库用的 objectbox ，数据类代码生成用的 freezed ，状态管理使用 GetX ，服务定位模式用 get_it ，主要目的是不想手写那么多模板代码了，哈哈
