### ISSUE TITLE
运行不成功

### ISSUE THREAD

**Issue by yxiangTang** [AmosHuKe/Mood-Example#13]
flutter 3.3.0
![image](https://user-images.githubusercontent.com/14209460/193010716-7aac73b7-13aa-4059-a6b1-fe24d3d62dd0.png)

**Comment by AmosHuKe** [comment]
感谢~
这个问题来自于 bonfire 这个库（游戏相关）

### 错误原因：
bonfire 进行了破坏性更新，但作者只更新了小版本号，会导致在 `flutter pub get` 获取依赖时自动更新到最新的小版本，导致一些组件无法使用。

### 解决方式：
以下两种方式仍选其一
方式1：在 `pubspec.yaml` 中将 `bonfire: ^2.6.1` 修改为 `bonfire: 2.6.1`，然后 `flutter clean` 清理构建，最后 `flutter pub get` 重新获取依赖。
方式2：不要删除 `pubspec.lock` 文件，就算编辑器提示自动更新也不要去点，然后 `flutter clean` 清理构建，最后 `flutter pub get` 重新获取依赖。
