### ISSUE TITLE
ios开启小程序报错

### ISSUE THREAD

**Issue by realdonaldtrump2** [AmosHuKe/Mood-Example#15]
Could not build the precompiled application for the device.
Error (Xcode): Library not found for -llibNavigator

**Comment by AmosHuKe** [comment]
解决办法在这里，[在 iOS 无法打开 uni小程序或无法使用 UniMPSDK](https://github.com/AmosHuKe/Mood-Example#q-%E5%9C%A8-ios-%E6%97%A0%E6%B3%95%E6%89%93%E5%BC%80-uni%E5%B0%8F%E7%A8%8B%E5%BA%8F%E6%88%96%E6%97%A0%E6%B3%95%E4%BD%BF%E7%94%A8-unimpsdk)
