### ISSUE TITLE
🤔️ 常见问题

### ISSUE THREAD

**Issue by AmosHuKe** [AmosHuKe/Mood-Example#16]
[链接](https://github.com/AmosHuKe/Mood-Example#%EF%B8%8F-%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98)

**Comment by yendiscart** [comment]
What is the app backend? Is it connected to any server ?

**Comment by AmosHuKe** [comment]
> What is the app backend? Is it connected to any server ?

@yendiscart This is just a local client, with no server connection, the database is [sqfile](https://pub.dev/packages/sqflite).
