### ISSUE TITLE
背景图片

### ISSUE THREAD

**Issue by lsdlh** [AmosHuKe/Mood-Example#17]
卡片上的背景图片是怎么制作的？

**Comment by lsdlh** [comment]
> Stack + Positioned 就好啦 类似下面这样
> 
> https://github.com/AmosHuKe/Mood-Example/blob/f11e8d2d23e1f04ec65b484a7524b0775991da76/lib/views/home/index.dart#L436-L581
我的意思是图片是你自己设计的吗，哪里能找到这种素材，比如功能更新那个火箭图片

**Comment by AmosHuKe** [comment]
README 里有写，是来自 icons8 的插画，https://icons8.com/illustrations
如果要免费使用他们的内容，注意要标注版权噢~

**Comment by lsdlh** [comment]
> README里有写，是来自icons8的插画， https: [//icons8.com/illustrations](https://icons8.com/illustrations) 如果要免费使用他们的内容，注意要标示版本哦~

ok谢谢

**Comment by lsdlh** [comment]
老哥你是开订阅了吗，能不能帮我下个图标

**Comment by AmosHuKe** [comment]
> 老哥你是开订阅了吗，能不能帮我下个图标

没有开订阅，都下载的免费内容

**Comment by lsdlh** [comment]
ok
