### ISSUE TITLE
在安卓設備中運行出現白屏

### ISSUE THREAD

**Issue by 540765** [AmosHuKe/Mood-Example#18]
flutter：3.x.x
![微信截图_20230829184122](https://github.com/AmosHuKe/Mood-Example/assets/65942529/714bc285-58ed-48cb-871d-f8264f2b23c9)

**Comment by 540765** [comment]
補充，是出現在打開小程序中，所有小程序都出現白屏情況

**Comment by AmosHuKe** [comment]
@540765 我测试 Flutter 3.13.1 没有复现你的问题。
控制台是否报错？

**Comment by 540765** [comment]
@AmosHuKe 控制台没有报错，所以很难排查，目前遇到的是小程序tabbar可以显示，页面为白屏，我是按照你的bloc来的，我再尝试一下，或许是我漏了哪些配置

**Comment by 540765** [comment]
我尝试新建了一个demo，,控制台信息如下：
![微信截图_20230830101538](https://github.com/AmosHuKe/Mood-Example/assets/65942529/8d41b2a9-3b29-4a28-8b50-79ed0bad27ce)

**Comment by AmosHuKe** [comment]
@540765 你按照 blog 上自行配置的 (UniMPSDK 3.4.7) ？如果用的是官方最新的 SDK (UniMPSDK 3.8.12)，他们的配置方式会有些变化，请参照 [uni 小程序 SDK](https://nativesupport.dcloud.net.cn/UniMPDocs/UseSdk/android.html)

**Comment by AmosHuKe** [comment]
@540765 小程序打包基座 HBuilder X 的版本尽量与 UniMPSDK 一致，避免打包的小程序存在差异，
比如：UniMPSDK v3.8.12 与之对应的小程序打包基座 HBuilder X v3.8.12

**Comment by AmosHuKe** [comment]
感谢你的提问，
我先关闭此 issue ，目前测试多个机型没发现白屏的情况，或者还没确切复现方式，
后续如果有新的情况，我再重开此 issue。

**Comment by 540765** [comment]
好，我会再次尝试和记录详细情况，需要多些时间，是否有更直接与你交流的方式

**Comment by AmosHuKe** [comment]
在此回复，或是邮件沟通即可，方便统筹信息（如果其他人有与你相同的问题）。

**Comment by 540765** [comment]
请问iOS上如何配置，我已经安装官网来，但未成功运行，经常遇到下面包问题：
![image](https://github.com/AmosHuKe/Mood-Example/assets/65942529/bef4f67d-cde1-4f1b-b34c-401d1ac5700f)

**Comment by AmosHuKe** [comment]
> 请问iOS上如何配置，我已经安装官网来，但未成功运行，经常遇到下面包问题：

@540765 
1、清理 Xcode 缓存
2、检查 Build Settings 中 Library Search Paths 的位置是否正确（UniMPSDK 的 Core Libs)

**Comment by 540765** [comment]
@AmosHuKe 我尝试后解决了，但是遇到了新问题，发现网上许多人和我一样，目前是闪退：
![image](https://github.com/AmosHuKe/Mood-Example/assets/65942529/bd2b8205-7fd4-4a10-9f9c-2f9afe7fa088)
主要问题：
+[WKWebView exchHookMethods]: unrecognized selector sent to class 0x112acf6c8
2023-09-05 18:40:56.366837+0800 Runner[91439:1177177] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '+[WKWebView exchHookMethods]: unrecognized selector sent to class 0x112acf6c8'
*** First throw call stack:
(
 0   CoreFoundation                      0x00007ff8004288ab __exceptionPreprocess + 242
 1   libobjc.A.dylib                     0x00007ff80004dba3 objc_exception_throw + 48
 2   CoreFoundation                      0x00007ff8004379d1 __CFExceptionProem + 0

**Comment by 540765** [comment]
是否遇到过这样的情况

**Comment by 540765** [comment]
我已经成功，很感谢你的项目，对我帮助很大

**Comment by 540765** [comment]
我使用过程中遇到一些问题，不知道朋友是否遇到，在真机中，app打开小程序后把主app close后，无法再从后台进入小程序。安卓12上

**Comment by a77uu** [comment]
> @AmosHuKe 我尝试后解决了，但是遇到了新问题，发现网上许多人和我一样，目前是闪退： ![image](https://private-user-images.githubusercontent.com/65942529/265872128-bd2b8205-7fd4-4a10-9f9c-2f9afe7fa088.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA2ODE4NDcsIm5iZiI6MTcxMDY4MTU0NywicGF0aCI6Ii82NTk0MjUyOS8yNjU4NzIxMjgtYmQyYjgyMDUtN2ZkNC00YTEwLTlmOWMtMmY5YWZlN2ZhMDg4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzE3VDEzMTkwN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWFiODE0OTNmMDhkNWY0ZDJjNGJhYzQxMTY5YWQ3YmJhOTczMDNmMTBhYjZmMWJkMmMyNGUzMmFmMWQwNmM4Y2QmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.hOZjwxrTI5mJgNKSGtp9VQF1HNks38_frAE39SInXcQ) 主要问题： +[WKWebView exchHookMethods]: unrecognized selector sent to class 0x112acf6c8 2023-09-05 18:40:56.366837+0800 Runner[91439:1177177] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '+[WKWebView exchHookMethods]: unrecognized selector sent to class 0x112acf6c8' *** First throw call stack: ( 0 CoreFoundation 0x00007ff8004288ab __exceptionPreprocess + 242 1 libobjc.A.dylib 0x00007ff80004dba3 objc_exception_throw + 48 2 CoreFoundation 0x00007ff8004379d1 __CFExceptionProem + 0

在自行集成3.99时也出现了这个情况，请问时如何解决的？
