### ISSUE TITLE
ios运行时报错"liblibweex"

### ISSUE THREAD

**Issue by malex911** [AmosHuKe/Mood-Example#21]
![image](https://github.com/AmosHuKe/Mood-Example/assets/136546224/2ae2525d-f0d5-4adc-9d12-2a89d125fb64)

**Comment by AmosHuKe** [comment]
@malex911 
我没有复现你的问题，不过看起来是 UniMPSDK 的问题。
我已经把 UniMPSDK 升级到了 3.98 最新版本，
你可以重新 clone 试试是否还存在这个问题。

**Comment by malex911** [comment]
已经解决了  现在有个小程序视频播放不了的问题

**Comment by AmosHuKe** [comment]
@malex911 
> 已经解决了 现在有个小程序视频播放不了的问题

这是因为项目中只集成了核心基础库（因为仅作为集成演示），
许多功能库（比如视频、地图、分享、支付、登录、直播pusher等SDK）没有集成，

如果你需要这些功能就需要自行集成。

比如在 iOS 中集成，需要先下载  [UniMP_iOS_SDK](https://nativesupport.dcloud.net.cn/UniMPDocs/SDKDownload/ios.html) ，
然后你会看见如下结构：
```
├── UniMPSDK
│   ├── Core          # 核心库
│   ├── Features      # 非核心功能库
......
```

之后根据以下两个官方教程进行集成：
- [iOS 核心库集成教程（可以看看，非核心库集成方式也是一致）](https://nativesupport.dcloud.net.cn/UniMPDocs/UseSdk/ios.html)
- [iOS 功能模块集成（包含所有库的教程和说明）](https://nativesupport.dcloud.net.cn/UniMPDocs/UseModule/ios/ios.html)

**Comment by malex911** [comment]
谢谢了   回复的真快

**Comment by AmosHuKe** [comment]
哈哈哈哈哈  周末愉快，
那就先关闭了。
