### ISSUE TITLE
如何实现非内置 uni小程序集成方式：应用资源包(.wgt)可以选择从云端获取或共享文件等方式，宿主通过 uni小程序 SDK 的 API 调用 releaseWgtToRunPath 实现释放资源包集成 uni小程序

### ISSUE THREAD

**Issue by openimchat** [AmosHuKe/Mood-Example#22]
官方也没有提供远程加载的方式，可以给出简单的实例代码么？

**Comment by AmosHuKe** [comment]
官方 API 示例：[DCUniMPSDK.getInstance().releaseWgtToRunPathFromePath(appid, wgtPath, callBack)](https://nativesupport.dcloud.net.cn/UniMPDocs/API/android-v2.html#dcunimpsdk-getinstance-releasewgttorunpathfromepath)

我还没有实际用过，你可以试试。

1、宿主通过远程的方式将 wgt 文件下载保存到 getExternalCacheDir().getPath() 路径。
2、调用 releaseWgtToRunPathFromePath 进行 wgt 释放。
3、调用 startApp 打开。

**Comment by openimchat** [comment]
你还没有封装releaseWgtToRunPathFromePath接口的实现，可以简单实现一下吗？😄

**Comment by AmosHuKe** [comment]
这个就需要你自行去尝试一下了 😺，官方有示例代码，Android 原生代码实现一下~

**Comment by openimchat** [comment]
加个QQ呗，有偿帮忙实现一下，我不太懂安卓和IOS。😁

**Comment by AmosHuKe** [comment]
非常抱歉 😂，暂时没啥时间，可以找找其他懂安卓和 iOS 的看看。
